version: 2
jobs:
  update-and-publish:
    docker:
      - image:  circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Get the data
          command: |
            bash get_data.sh
      - run:
          name: Publish on data.gouv
          command: |
            bash upload.sh

workflows:
    version: 2
    weekly:
        jobs:
            - update-and-publish
        triggers:
            - schedule:
                cron: 10 10 * * *
                filters:
                    branches:
                        only:
                            - master
